### PR TITLE
fix OpenSSL compatibility  and cert bug

### PR DESCRIPTION
**Pull request by SeaHOH**
https://github.com/XX-net/XX-Net/issues/8852#issuecomment-350542494
#8941
#8943
#8946
#8958 
#8962

### CODE REVIEW

**Comment by xxnet** [comment]
测试：
 Fedora22 下测试：
[launcher][INFO] use build-in openssl lib

  File "/XX-Net/code/default/gae_proxy/start.py", line 18, in main
    client.main()
  File "/XX-Net/code/default/gae_proxy/local/proxy.py", line 153, in main
    CertUtil.init_ca()
  File "/XX-Net/code/default/gae_proxy/local/cert_util.py", line 637, in init_ca
    context = ssl.SSLContext(ssl.PROTOCOL_TLS)
AttributeError: 'module' object has no attribute 'PROTOCOL_TLS'


Ubunt14 下测试通过。

Debian 7.7 测试通过

Debian 8
/XX-Net/code/default/gae_proxy/local/cert_util.py", line 637, in init_ca
    context = ssl.SSLContext(ssl.PROTOCOL_TLS)
AttributeError: 'module' object has no attribute 'PROTOCOL_TLS'

Debian 9
 /XX-Net/code/default/gae_proxy/local/cert_util.py", line 639, in init_ca
    context.load_cert_chain(cert, CertUtil.cert_keyfile)
TypeError: coercing to Unicode: need string or buffer, X509 found

**Comment by SeaHOH** [comment]
改成 `PROTOCOL_TLSv1` 应该可以。

>TypeError: coercing to Unicode: need string or buffer, X509 found

这个 TypeError 想不通，X509 才是对的啊。

**Comment by xxnet** [comment]
637行, 改成  PROTOCOL_TLSv1 测试通过。
​


639行：
根据 https://docs.python.org/3/library/ssl.html
里的定义：
  SSLContext.load_cert_chain(*certfile*, *keyfile=None*, *password=None*)¶
<https://docs.python.org/3/library/ssl.html#ssl.SSLContext.load_cert_chain>



改成：

context.load_cert_chain(filename, CertUtil.cert_keyfile)

就可以

**Comment by xxnet** [comment]
​Ubuntu 14:
File "/XX-Net/code/default/gae_proxy/local/cert_util.py", line 637, in
init_ca
    context = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
AttributeError: 'module' object has no attribute 'SSLContext'

**Comment by SeaHOH** [comment]
对了，应该是文件名，我一直没反应过来……
但是 Ubuntu 14 是什么情况？

**Comment by xxnet** [comment]
​ Ubuntu 14 似乎是 ssl库太老了。
 能否不要用ssl库，全部用OpenSSL 库

**Comment by SeaHOH** [comment]
刚试过，可以。

**Pull request merged**
