### PR TITLE
i18n completed with en_US and zh_CN

### PR DESCRIPTION
**Pull request by mikedchavez1010**
The i18n foundation work was done, with fully  en_US and zh_CN support.

### CODE REVIEW

**Comment by xxnet** [comment]
how to generate/upate the pot file after add text in html?

2015-12-15 18:54 GMT+08:00 mike <notifications@github.com>:

**Comment by xxnet** [comment]
XX-Net/gae_proxy$ pybabel extract -F babel.config -o lang/messages.pot .
Is this right?

2015-12-15 20:51 GMT+08:00 Net XX <xxnet.dev@gmail.com>:

**Comment by xxnet** [comment]
I think we need a script to update everything automatic.

2015-12-15 20:56 GMT+08:00 Net XX <xxnet.dev@gmail.com>:

**Comment by xxnet** [comment]
.mo是二进制文件，放在git上效率很低

能否跳过mo文件，在需要时才去生成？
这样下载包也小了。

包括生成的.po/.pot文件，前面的注释必要性也不大，经常造成git的变动，我想改改库总能解决。

2015-12-15 21:00 GMT+08:00 Net XX <xxnet.dev@gmail.com>:

**Comment by xxnet** [comment]
奇怪有些字段没有翻译出来，比如 Start deploy

2015-12-16 7:05 GMT+08:00 Net XX <xxnet.dev@gmail.com>:

**Comment by xxnet** [comment]
2015-12-16 8:08 GMT+08:00 Net XX <xxnet.dev@gmail.com>:

> 奇怪有些字段没有翻译出来，比如 Start deploy
>
>>
>>
找到原因了，po文件中fuzzy字段删除后，重新生成mo文件就好了，已经解决。

**Comment by mikedchavez1010** [comment]
Glad that zlsun added the language switch combo box on the master branch.
Seems buggy. Hope I help fix the bug.
-----------------------------------------------------------------
Author: zlsun <zlsun1995@gmail.com>
Date:   Tue Dec 22 17:33:09 2015 +0800

    Add dropdown list for switching languages.


2015-12-16 9:18 GMT+08:00 Michael.X <notifications@github.com>:

**Comment by xxnet** [comment]
I have fix a little bug and push to github, check it before start your work.

2015-12-22 22:11 GMT+08:00 mike <notifications@github.com>:

**Comment by mikedchavez1010** [comment]
Thanks for your notification. Will keep an eye on the master update. I'm
afraid it'll cost me days to understand your creative launcher framework
completely. Merry Christmas! And may God bless you.

**Comment by xxnet** [comment]
​ Merry Christmas!

**Comment by mikedchavez1010** [comment]
Is the test version the same with the master branch? How do you keep them
in sync?

**Comment by xxnet** [comment]
XX-Net don't need compile, just the source code is the release.
So the source package zip file can be used as a release package.

When I release a version, I edit the README.md test version line, then
commit, push to github.
then create a release version on github.
github create a git tag then create a source package. It used as release
package in XX-Net.
User just download the source code zip file as the release package.

When one version is stable enough, I edit the README.md Stable version line
in github.

The launcher check the local README.md Test version line as local version.

The launcher check the github README.md Test version/Stable version for
auto update.


Hope you can understand what I said.

​

**Comment by mikedchavez1010** [comment]
No problem. Thanks for sharing.

**Pull request merged**
