### PR TITLE
Merge i18n feature, please

### PR DESCRIPTION
**Pull request by mikedchavez1010**
Please merge the initial i18n feature, which was tested successfully on both Ubuntu (English, 32 and 64 bit versions) and Windows 7 (English & Chinese versions).
1. As i18n-related packages jinja2, markupsafe, babel, pytz are OS-independent, they reside in folder python27/1.0/lib/noarch.
2. Appended modules decimal.py and numbers.py were copied from Python 2.7 code on Windows, so they were put in folder python27/1.0/lib which is for Windows exclusively.

### CODE REVIEW

**Comment by simonasd** [comment]
这段时间很忙没有来github看看，居然发生了这么大的事情！！（窃喜）

如果我没有理解错的话，应该是实现了期待很久的基于jinja2的国际化！！？？@mikedchavez1010 请收下膝盖

**Comment by xxnet** [comment]
I will merge my change later.
Big change, refactor the log system and http_server/cient lib.

在 2015年12月11日 上午1:15，simonasd <notifications@github.com>写道：

**Comment by xxnet** [comment]
wiki i18n needed.
We can setup a simple guild page and all page referenced by web_ui at
beginning.
So wiki need a i18n frame too: sub path? or prefix?

在 2015年12月11日 上午6:17，Net XX <xxnet.dev@gmail.com>写道：

**Comment by simonasd** [comment]
@xxnet Github Wiki is now simple and crude. I don't know how to review recent activity, and there are no category, no interlanguage links, no catalog, we have to do everything manually.

Maybe we can try a build in wiki ?

Anyway, let's build Rome :laughing:

**Comment by simonasd** [comment]
@mikedchavez1010 @xxnet Would you please help me with this problem?

I'm trying to simplify status.html for user, but I don't fully understand how the template work. I use {{ _( "this format" ) }} in the html, then update messages.pot / messages.po. Everything goes well but the translation doesn't work, they're still in English. You can check https://github.com/simonasd/XX-Net/tree/patch-1 for my current code.

**Comment by xxnet** [comment]
@simonasd
Do you have read jinjia2 document?
I thing there should be some idea for it.
I have not study it.

@mike
  Maybe you should write some guild for this.




2015-12-11 23:59 GMT+08:00 simonasd <notifications@github.com>:

**Comment by simonasd** [comment]
@xxnet my bad, I forgot the .mo file. Google tolds me how to do this:

1. [PoEditor](https://poedit.net/) can automatically build .mo file while you saving .po file.

2. Or, you can  download the "[gettext](https://www.gnu.org/software/gettext/)" GNU toolkit, and then use

<code>msgfmt messages.po</code>

to build messages.mo from messages.po.

**Comment by xxnet** [comment]
mike add a shell: pybabel_update.sh in each module path.

what is the function in this script？

2015-12-13 13:09 GMT+08:00 simonasd <notifications@github.com>:

**Comment by simonasd** [comment]
@xxnet 
It looks like a developer's tool, contents several lines like this:
<code>pybabel update -l de_DE -d ./lang -i ./lang/messages.pot</code>

messages.pot is a general template. That script using pybabel to create untranslated messages.po for specific language. I guess we can remove this kind of script.

**Comment by xxnet** [comment]
研究了pybabel
安装：
sudo pip2 install Flask-Babel
​
作用：
将lang目录下的pot文件更新到各目录下的po文件。
解释：
  每次开发增加、修改显示的字符后，手动编辑 lang/messages.pot文件，pot的意思是po 的template模板
  比如新增了一个字符串： "Thanks all developer"
  那么相应的要在所有翻译语言的po文件下去增加对应的条目，手动维护太麻烦而且容易出错，pybabel_update.sh 就是自动更新的脚本。

刚才在https://hosted.weblate.org 申请了项目，还在审批中。

**Comment by mikedchavez1010** [comment]
Hello, everyone,

Sorry for my slow response.

1. Please read the comments added at the beginning of the i18n module
launcher/jinja2_i18n_helper.py, which describe howtos. Going to create an
i18n demo repo on Github to show how to do this.

2. Libraries python-babel and python-jinja2 have to be installed in the
development environment.

3. pybabel_update.sh (in both launcher/ and gae_proxy/) is used to simplify
the updating of all the supporting languages in order not to run  "pybabel
update ..." against each one.

4. Modules launcher and gae_proxy are internationalized independently,
using the same module launcher/jinja2_i18n_helper.py.


Note 1: "pybabel -v extract ..." has to be run each time when new strings
are added in the template files(*.html & *.yaml), tagged with {{
_("string_to_be_translated") }}.

Note 2: Running pybabel init ... against each language only once to create
the *.po file.

Note 3: Update the incremental modifications with "pybabel update ...",
thereafter. And shell file (Linux only) pybabel_update.sh makes this
simpler.  All the existing translated strings will be gone is pybabel init
... is used!

Note 4: After all the translations are done, run "pybabel compile -f -d
./lang" to re-compile all the *.po files to *.mo files. This will compile
all the existing languages and no need to compile one by once.


By the way, thank you for your praise. Let's polish this tool together.

Mike

2015-12-15 9:45 GMT+08:00 Michael.X <notifications@github.com>:

**Comment by xxnet** [comment]
You can put this guild to github wiki.
I have update the pybabel_update.sh to do all the work, you can check the
trunk.

And I just write a simple and stupid i18n render, so we don't need .mo file
anymore.
I have pushed to trunk, test it and give feedback, thank you!

2015-12-16 23:24 GMT+08:00 mike <notifications@github.com>:

**Comment by mikedchavez1010** [comment]
@simonasd I don't use PoEditor, which might be better than a textual editor. I just use any textual editor to edit the *.po files, and then, pybabel compile. Since @xx-net created a render to do this, i18n work will surely be simplified further. Let's test and improve @xxnet 's revision.

**Comment by mikedchavez1010** [comment]
@xxnet, I'm running and reading your improvement upon i18n implementation. Yours is very clever and makes the whole tool lightweight. Since your implementation is quite different from my original one, it's necessary for me to create a repo to showcase mine just in case it's of help for others. 

By the way, it will take me days before I know how to create Github wiki pages. Thanks for your devotion.

**Comment by simonasd** [comment]
@mikedchavez1010 Actually I don't use PoEditor either, that's from google. And again, I'm really exciting about the work you two have done. This project are now helping people from all over the world! Think about that! :laughing:

**Comment by mikedchavez1010** [comment]
Hi, @simonasd,

Yes. That's the spirit of FOSS - sharing with others. Let's contribute a
little bit in our own way to the collapsing of Berlin Wall.

Michael's i18n implementation is very creative and lightweight. I enjoy
that very much. Planning to delete my implementation and keep Michael's,
instead. Hopefully, this will be done in the following weeks.

Mike

**Comment by xxnet** [comment]
I try to read the source code of jinja2 and understand how it work, found
that jinja2 is a general template framework, not only for translation.
Jinja2 can do the work that web_control.py do: generate html from
index.html/menu.yaml and right content, and more powerful.
We just need a simple key word/dictionary  replacement.

The standard to define translation is good enough for us, so I keep
compatible with jinja2 and gettext.
Also I remove the line comment in po file to keep git clean when we just
change the line number.

.pot file removed too, we don't need it in git.

We can remove the jinja2 libs if this works fine.

**Comment by mikedchavez1010** [comment]
Michael.X,

I agree. You're amazingly smart. Your implementation makes git extremely
happy! I'll extract my implementation as a repo in case it's useful for
those who need it. Hopefully, I'll complete this in the coming weekend.

I'v modified the new Advance menu, i.e., renaming it to Advanced. Will send
a pull request soon.

Seems at least the locale for en_US, zh_CN, fa_IR (Iranian Persian) should
be enabled.

Mike Chavez

**Pull request merged**
