### PR TITLE
Rename advance.html to advanced.html

### PR DESCRIPTION
**Pull request by mikedchavez1010**
"Advance" should be "Advanced" in gae_proxy/web_ui. All the related strings have been modified accordingly. Many conflicts? My fault? Shall I fix them first?

### CODE REVIEW

**Comment by mikedchavez1010** [comment]
Many conflicts?

**Comment by xxnet** [comment]
Yes, You need update to trunk then commit pull.

And If msgid is English ready, we don't need to enable English po?

And If other translation is not ready, we don't need to enable it?

**Comment by mikedchavez1010** [comment]
OK. en_US will be disabled. zh_CN & fa_IR are ready and enabled. I'll pull your master and send a new pull request.

**Comment by mikedchavez1010** [comment]
This request is obsolete. A new one will be created.

**Comment by mikedchavez1010** [comment]
OK.  Please keep an eye on my new pull request. jinja2-based i18n
implementation removed!

**Pull request closed without merging**
