### PR TITLE
Use new style exceptions in both Python 2 and Python 3

### PR DESCRIPTION
**Pull request by cclauss**
Old style exceptions are syntax errors in Python 3 but new style exceptions work as expected in both Python 2 and Python 3.  🎄

### CODE REVIEW

**Comment by SeaHOH** [comment]
This doesn't make sense unless you can run it in python3 after patched.

**Comment by cclauss** [comment]
A port to Python 3 in a single pull request would touch too many files and would be rejected as too complex.  Incrementalism is the only way that works.

**Comment by SeaHOH** [comment]
I don't think so, merge into master branch is not a good idea.
If you want to a python3 version, I can creat a new branch for this, you can work on this basis.

**Comment by cclauss** [comment]
Separate branches lead to _Big Bang merges_ which always fail on large code bases that need to support both Python 2 and Python 3.  When I said that incrementalism was the way to go, I meant it. 124 days until Python 2 end of life.

**Comment by SeaHOH** [comment]
You don't need to support python2, focus on python3 if you want it.

**Pull request closed without merging**
