### PR TITLE
Remove jinja2-based i18n implementation & its dependencies

### PR DESCRIPTION
**Pull request by mikedchavez1010**
Remove jinja2-based i18n implementation & its dependencies

1. Mike Chavez's i18n implementation, module launcher/jinja2_i18n_helper.py removed.

2. From folder python27/1.0/lib/noarch, dependency packages babel, jinja2, markupsafe & pytz removed.

3. From python27/1.0/lib, dependency modules decimal.py & numbers.py removed.

4. babel.config & pybabel_update.sh are kept in both launcher and gae_proy folders as they contintue functioning in the following i18n work.

5. Old non-i18n code lines and jinja2-based i18n code lines in launcher/web_control.py removed.

6. Michael.X's i18n implementation launcher/simple_i18n.py employed, which avoids the use of binary *.mo files and clean up the *.po files so as to make as little as possible change to the source files and relax Git. The *.pot files are ignored by Git, too, which was set by Michael.X.

7. fa_IR (Iranian Persian) added. 3 languages en_US, zh_CN and fa_IR are supported. en_US turned off.

8. Many minor modifications to the UI strings.

Bug alert: Please have a look at bug #1638

### CODE REVIEW

**Comment by mikedchavez1010** [comment]
Thanks. A new pull request sent. A supported language list was added to
README.md.

**Comment by xxnet** [comment]
Merged.
Good job..

Sync code, solve conflict before pull next time.
​

**Comment by mikedchavez1010** [comment]
Already Done! Thanks. Going to add a language switch on the web UI. Have a
nice weekend.

**Comment by xxnet** [comment]
good idea, have language switch on web_ui, and remember on config would be
better.

2015-12-19 23:39 GMT+08:00 mike <notifications@github.com>:

**Comment by mikedchavez1010** [comment]
Got it. Thanks.

**Pull request merged**
