### PR TITLE
精简部署 bat 传输全部参数的方法

### PR DESCRIPTION
**Pull request by Cat7373**
这样可以保证所有参数都被传输到 py 脚本里。
另外我这里部署也有问题(https://github.com/XX-net/XX-Net/issues/3398) - -
根本就没弹出授权网页来。

    *****\XX-Net\code\default\gae_proxy\server>uploader.bat xxnet-1 -password 123123 -debug -xxx

    *****\XX-Net\code\default\gae_proxy\server>..\..\python27\1.0\python.exe uploader.py xxnet-1 -password 123123 -debug -xxx
    2016-05-16 11:39:57,901 - root - INFO - use rc4_password: 123123
    2016-05-16 11:39:57,901 - root - INFO - enable debug logging
    2016-05-16 11:39:57,901 - root - INFO - unknow argv: -xxx
    2016-05-16 11:39:57,901 - root - INFO - set proxy to http://127.0.0.1:8087
    2016-05-16 11:39:57,901 - root - INFO - ============  Begin upload  ============
    2016-05-16 11:39:57,901 - root - INFO - appid:xxnet-1
    11:39 AM Application: xxnet-1
    11:39 AM Host: appengine.google.com
    11:39 AM Rolling back the update.
    2016-05-16 11:39:57,938 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'xxnet-1'}
    2016-05-16 11:39:57,938 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate skipped auth; needs_auth=False
    2016-05-16 11:39:57,938 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=xxnet-1&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
    2016-05-16 11:39:59,355 - google.appengine.tools.appengine_rpc - DEBUG - Got http error 404.
    2016-05-16 11:39:59,355 - google.appengine.tools.appengine_rpc - DEBUG - Unexpected results: {'date': 'Mon, 16 May 2016 03:40:00 GMT', 'status': '404', 'content-length': '1584', 'content-type': 'text/html; charset=UTF-8'}
    Error 404: --- begin server output ---
    <!DOCTYPE html>
    <html lang=en>
      <meta charset=utf-8>
      <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
      <title>Error 404 (Not Found)!!1</title>
      <style>
        *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
      </style>
      <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
      <p><b>404.</b> <ins>That鈥檚 an error.</ins>
      <p>The requested URL <code>/api/appversion/rollback</code> was not found on this server.  <ins>That鈥檚 all we know.</ins>
    --- end server output ---
    11:39 AM Application: xxnet-1
    11:39 AM Host: appengine.google.com
    11:39 AM Rolling back the update.
    2016-05-16 11:39:59,437 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'xxnet-1'}
    2016-05-16 11:39:59,438 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate skipped auth; needs_auth=False
    2016-05-16 11:39:59,440 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=xxnet-1&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
    2016-05-16 11:40:00,457 - google.appengine.tools.appengine_rpc - DEBUG - Got http error 404.
    2016-05-16 11:40:00,457 - google.appengine.tools.appengine_rpc - DEBUG - Unexpected results: {'date': 'Mon, 16 May 2016 03:40:01 GMT', 'status': '404', 'content-length': '1584', 'content-type': 'text/html; charset=UTF-8'}
    Error 404: --- begin server output ---
    <!DOCTYPE html>
    <html lang=en>
      <meta charset=utf-8>
      <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
      <title>Error 404 (Not Found)!!1</title>
      <style>
        *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
      </style>
      <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
      <p><b>404.</b> <ins>That鈥檚 an error.</ins>
      <p>The requested URL <code>/api/appversion/rollback</code> was not found on this server.  <ins>That鈥檚 all we know.</ins>
    --- end server output ---
    11:40 AM Application: xxnet-1
    11:40 AM Host: appengine.google.com
    11:40 AM Rolling back the update.
    2016-05-16 11:40:00,539 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'xxnet-1'}
    2016-05-16 11:40:00,542 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate skipped auth; needs_auth=False
    2016-05-16 11:40:00,543 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=xxnet-1&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
    2016-05-16 11:40:01,441 - google.appengine.tools.appengine_rpc - DEBUG - Got http error 404.
    2016-05-16 11:40:01,441 - google.appengine.tools.appengine_rpc - DEBUG - Unexpected results: {'date': 'Mon, 16 May 2016 03:40:02 GMT', 'status': '404', 'content-length': '1584', 'content-type': 'text/html; charset=UTF-8'}
    Error 404: --- begin server output ---
    <!DOCTYPE html>
    <html lang=en>
      <meta charset=utf-8>
      <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
      <title>Error 404 (Not Found)!!1</title>
      <style>
        *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
      </style>
      <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
      <p><b>404.</b> <ins>That鈥檚 an error.</ins>
      <p>The requested URL <code>/api/appversion/rollback</code> was not found on this server.  <ins>That鈥檚 all we know.</ins>
    --- end server output ---
    2016-05-16 11:40:01,457 - root - INFO - =======================
    2016-05-16 11:40:01,473 - root - INFO - Deploy failed appid list:
    2016-05-16 11:40:01,473 - root - INFO - - xxnet-1
    2016-05-16 11:40:01,473 - root - INFO - == END ==

### CODE REVIEW

**Comment by xxnet** [comment]
部署失败时，GAE的日志什么？

**Comment by Cat7373** [comment]
qq 20160516141837
翻日志的时候看到这么一条，怀疑与[这个](https://github.com/XX-net/XX-Net/issues/3388)问题有关

**Comment by Cat7373** [comment]
XX-Net 日志(debuginfo = 1 已开)

    May 16 11:39:56.617 - [DEBUG] get ip:24.214.95.156 t:527
    May 16 11:39:57.602 - [DEBUG] create_ssl update ip:24.214.95.156 time:651 h2:0
    May 16 11:39:57.602 - [DEBUG] get ip:66.187.114.84 t:529
    May 16 11:39:58.656 - [DEBUG] create_ssl update ip:66.187.114.84 time:700 h2:0
    May 16 11:39:59.356 - [INFO] GAE t:984 s:1584 POST https://74.125.23.101/api/appversion/rollback?app_id=xxnet-1&force_rollback=0&version=1 get_response:984
    May 16 11:40:00.457 - [INFO] GAE t:1000 s:1584 POST https://74.125.23.101/api/appversion/rollback?app_id=xxnet-1&force_rollback=0&version=1 h2_get_head:984,h2_finish[SP:106999]:16
    May 16 11:40:01.441 - [INFO] GAE t:878 s:1584 POST https://74.125.23.101/api/appversion/rollback?app_id=xxnet-1&force_rollback=0&version=1 get_response:877

**Comment by xxnet** [comment]
​怎么rollback 的host 是ip?
难道本地域名解析了？

**Comment by xxnet** [comment]
ip是google 的，但是这样的请求，估计google 的服务器不会给正确的返回。
​

74.125.23.101United States CaliforniaMountain View

**Comment by xxnet** [comment]
​win10 才能重现吗？

**Comment by Cat7373** [comment]
从出问题到现在没重启过 XX-Net
其他操作系统未测试，我手头也没有其他操作系统的电脑，也没装虚拟机

hosts 已检查没问题
DNS 服务器是 8.8.8.8 备用 114.114.114.114
proxy.ini 经过 git 检查无改动
manual.ini

    [listen]
    debuginfo = 1

    [pac]
    enable = 0

    [google_ip]
    ;max_good_ip_num = 9000

    [connect_manager]
    ;https_max_connect_thread = 8
    ;https_connection_pool_max = 30

    [system]
    log_file = 1

诊断信息

    sys-platform: AMD64, Windows-10-10.0.10586
    os-system: Windows
    os-version: 10.0.10586
    os-release: 10
    os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
    architecture: 32bit,WindowsPE
    browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36
    xxnet-version: 3.1.16

    python-version: 2.7.11
    openssl-version: 16.0.0 TLSv1_2 h2:alpn

    ipv6-status: 0
    gws-ip-num: total:4421 good:2001
    network-status: OK
    connected-link: new:2 used:0
    worker: h1:27 h2:3
    scan-ip-thread-num: 1
    ip-quality: 181
    is-idle: 0
    block-stat: OK
    proxy_state: OK
    ca_state: OK
    Appid_Working: true
    Appids_Out_Of_Quota: false
    Appids_Not_Exist: false
    Using_Public_Appid: false

**Comment by Cat7373** [comment]
C:\Users\********>ping appengine.google.com

    正在 Ping www3-china.l.google.com [74.125.23.100] 具有 32 字节的数据:
    请求超时。
    请求超时。
    请求超时。
    请求超时。

    74.125.23.100 的 Ping 统计信息:
        数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)

**Comment by Cat7373** [comment]
虽然看到似乎已经提交代码修复了。
不过还是提一下0.0
现在的 GAE SDK 是 [1.9.33](https://github.com/XX-net/XX-Net/blob/master/code/default/gae_proxy/server/lib/VERSION)，最新的是 [1.9.37](https://cloud.google.com/appengine/docs/python/release-notes)，可以考虑升级 0.0

**Comment by Cat7373** [comment]
好像时间跨度也不是很大- -

**Comment by xxnet** [comment]
域名本地解析了，我改了部署库的代码，强制远程解析域名，代码在master上，请测试

**Comment by Cat7373** [comment]
试了一次，成功重现问题，然后 git 同步到最新版本后，问题无法重现。

**Comment by xxnet** [comment]
估计就是这个问题了，可以发个新版给大家看看

**Pull request merged**
